### ISSUE TITLE
请问 这个可以接收摄像头的实时传过来的数据吗，然后实时给出分类结果

### ISSUE THREAD

**Issue by MachineLearning11** [FingerRec/real_time_video_action_recognition#12]

**Comment by FingerRec** [comment]
可以的，如果有GPU的话，GPU上是没有时延的，

**Comment by MachineLearning11** [comment]
谢谢你的回复！这对我有很大帮助，他是如何接受数据呢，是输入一帧还是输入很多帧，假如是输入很多帧的话 也可以实时吗，

**Comment by FingerRec** [comment]
仔细读real_time_c3d.py 这个文件哈，是读N帧作为一个clip feed到网络里。 多张是可以实时的，temporal window slide自己控制下
