### ISSUE TITLE
please input the video path to be classification:test_video/1.avi

### ISSUE THREAD

**Issue by hyaxzz** [FingerRec/real_time_video_action_recognition#8]
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on pretrained_model/sports1m_finetuning_ucf101.model: Not found: FindFirstFile failed for: pretrained_model : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3
; No such process
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

**Comment by FingerRec** [comment]
Please download the pretrained model offered and put it into correct location.
